### ISSUE TITLE
Python3 bytes-like issue

### ISSUE THREAD

**Issue by wolfthefallen** [zeroSteiner/smoke-zephyr#1]
Issue when saving a json file in python3.

---

How to recreate

make info.json file:

```
{
"name": "fswb",
"version": 1.0,
"update.dev": null,
"update.tools": null,
"update.image": null
}
```

run python3 and do the following commands

```
python3
from smoke_zephyr.configuration import Configuration
info_config = Configuration('info.json')
info_config.get('name') # not necessary but used to show the json loads.
info_config.save()
```

Sample stack trace

```
>>> from smoke_zephyr.configuration import Configuration
>>> info_config = Configuration('info.json')
>>> info_config.get('name')
'fswb'
>>> info_config.save()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/smoke_zephyr/configuration.py", line 203, in save
    file_h.write(self._serializer('dumps', self._storage))
TypeError: a bytes-like object is required, not 'str'
>>>
```

**Comment by zeroSteiner** [comment]
Fixed in commit 5d6ab3f0321c5025c19f8760ac12928068a25282 / v1.0.3 which will be tagged and released shortly.
